---
- name: Microsoft365 DSC
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:

    - name: Install Nuget update
      win_shell: Install-PackageProvider -Name NuGet -Force

    - name: Install Microsoft365 Module
      win_psmodule:
        name: Microsoft365DSC
        state: present


    - name: Microsoft365DSC example
      win_dsc:
        resource_name: O365Group
        DisplayName: "Ansible Test"
        MailNickName: "AnsibleTest"
        Description: "Ansible Test"
        ManagedBy: "{{ o365_username }}"
        Ensure: present
        GlobalAdminAccount_password: "{{ o365_password }}"
        GlobalAdminAccount_username: "{{ o365_username }}"
