---
- name: Microsoft365 DSC
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:
    - name: Install Microsoft365 Module
      win_shell: Install-Module -Name Microsoft365DSC -Force
    #   delegate_to: "{{ hostname }}"

    - name: Microsoft365DSC example
      win_dsc:
        resource_name: Microsoft365DSC
        name: O365Group
        DisplayName: "Ansible Test"
        MailNickName: "AnsibleTest"
        Ensure: present
    #   delegate_to: "{{ hostname }}"

