---
- name: Microsoft365 DSC
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:

    - name: Install Nuget update
      win_shell: Install-PackageProvider -Name NuGet -Force

    - name: Install Microsoft365 Module
      win_shell: Install-Module -Name Microsoft365DSC -Force

    - name: Microsoft365DSC example
      win_dsc:
        resource_name: Microsoft365DSC
        name: O365Group
        DisplayName: "Ansible Test"
        MailNickName: "AnsibleTest"
        Ensure: present
